### ISSUE TITLE
โหดจังครับสอนหน่อย

### ISSUE THREAD

**Issue by ReiiYuki** [PaiizZ/Final-Project#1]
โหดจังก๊าบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบบ สอนหน่อยๆ

**Comment by PaiizZ** [comment]
มิงเมาปะเนี้ยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยยย

**Comment by ReiiYuki** [comment]
ไม่เมา　！！！！

**Comment by gunhappy** [comment]
ขี้โม้ววว
